config/routes.rb
Rails.application.routes.draw do
  root :to => "application#index"
  get 'work' => 'application#work', :as => :work
  get 'about' => 'application#about', :as => :about

    resources :user
    resources :wardrobe
    resources :like
    resources :outfit

  get '/auth/facebook', as: "facebook_login"
  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'signin' => 'application#signin', :as => :signin
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :user do
        resources :wardrobe
        resources :like
        resources :outfit
      end
      resources :batch
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  serialize :likes
  after_create :serialize_likes
  
  def serialize_likes
     self.likes = {type: nil, image: nil}
     self.save!
  end
end

app/controllers/api/v1/like_controller.rb
class Api::V1::LikeController < Api::ApiController
  include ActionController::MimeResponds

  def index
    respond_to do |format|
      @likes = Like.all
      format.json { render json:@likes}
    end
  end

  def show
    respond_to do |format|
      @user = User.find(params[:id])
      @like = Like.find(id = @user.id)
      format.json { render json:@like }
    end
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def index
  end
end

app/views/like/index.html.erb
<wrapper>
  <%= render 'layouts/header' %>
</wrapper>
<center>
  <nav>
    <%= link_to "Your Wardrobe", wardrobe_index_path%>
    <%= link_to "Your Outfits", outfit_index_path%>
    <%= link_to "Your Likes", like_index_path%>
  </nav>
  LIKE PAGE
  <div class="box">
    <div class="like">
    </div>
  </div>
</center>
<wrapper>
  <%= render "application/footer.html.erb"%>
</wrapper>